import "./globals.css"; // Tailwind CSSをインポート

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="bg-red-300 p-4">メインレイアウト</div>
        {children}
      </body>
    </html>
  );
}
